# Generated by Django 4.0.4 on 2022-06-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_destino_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinos'),
        ),
    ]
