# Generated by Django 4.0.4 on 2022-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_destino_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
