# Generated by Django 4.0.4 on 2022-06-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='nombre',
        ),
    ]
