# Generated by Django 4.0.4 on 2022-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_rename_name_hotel_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='provincia',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='hotel',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
    ]
